<a href="https://colab.research.google.com/github/crisdouglasb-gg/-colab-sales-dataset-cleaning/blob/main/rag_pandas_mistral.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# =========================
# INSTALACIÓN CORRECTA
# =========================

!pip install -q langchain
!pip install -q langchain-experimental
!pip install -q langchain-community
!pip install -q langchain-openai
!pip install -q mistralai

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-sdk 1.42.1 requires opentelemetry-api==1.42.1, but you have opentelemetry-api 1.39.1 which is incompatible.
opentelemetry-sdk 1.42.1 requires opentelemetry-semantic-conventions==0.63b1, but you have opentelemetry-semantic-conventions 0.60b1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.39.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.

In [ ]:
# =========================
# IMPORTACIONES
# =========================

import pandas as pd
import os

from google.colab import files

from langchain_experimental.agents import create_pandas_dataframe_agent

from langchain_openai import ChatOpenAI

print("Importaciones correctas")

Importaciones correctas

In [ ]:
# =========================
# API KEY
# =========================

os.environ["OPENAI_API_KEY"] = " oVPAmUypyOm9Ps8zLteoeJsJQ7EiDaLd"

print("API KEY cargada")

API KEY cargada

In [ ]:
# =========================
# CONFIGURAR MISTRAL
# =========================

llm = ChatOpenAI(
    model="mistral-small",
    base_url="https://api.mistral.ai/v1",
    api_key=os.environ["OPENAI_API_KEY"],
    temperature=0
)

print("Modelo Mistral conectado")

Modelo Mistral conectado

In [ ]:
# =========================
# SUBIR DATASET
# =========================

uploaded = files.upload()

Saving sales_data_sample.csv to sales_data_sample (2).csv

In [ ]:
# =========================
# LEER CSV
# =========================

df = pd.read_csv("sales_data_sample.csv", encoding="latin1")

print("Dataset cargado correctamente")

df.head()

Dataset cargado correctamente

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [ ]:
# =========================
# DIAGNÓSTICO
# =========================

print("Dimensiones:")
print(df.shape)

print("\nColumnas:")
print(df.columns)

print("\nTipos de datos:")
print(df.dtypes)

print("\nValores nulos:")
print(df.isnull().sum())

Dimensiones:
(2823, 25)

Columnas:
Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
       'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE',
       'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE',
       'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME',
       'DEALSIZE'],
      dtype='object')

Tipos de datos:
ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE            object
STATUS               object
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE          object
MSRP                  int64
PRODUCTCODE          object
CUSTOMERNAME         object
PHONE                object
ADDRESSLINE1         object
ADDRESSLINE2         object
CITY                 object
STATE                object
POSTALCODE           object
COUNTRY              object
TERRITORY            object
CONTACTLASTNAME      object
CONTACTFIRSTNAME     object
DEALSIZE             object
dtype: object

Valores nulos:
ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [ ]:
# =========================
# NORMALIZACIÓN
# =========================

# eliminar duplicados
df = df.drop_duplicates()

# rellenar valores nulos
df = df.fillna("DESCONOCIDO")

# limpiar nombres de columnas
df.columns = df.columns.str.lower()

df.columns = df.columns.str.replace(" ", "_")

print("Datos normalizados")

df.head()

Datos normalizados

,ordernumber,quantityordered,priceeach,orderlinenumber,sales,orderdate,status,qtr_id,month_id,year_id,...,addressline1,addressline2,city,state,postalcode,country,territory,contactlastname,contactfirstname,dealsize
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,DESCONOCIDO,NYC,NY,10022,USA,DESCONOCIDO,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,DESCONOCIDO,Reims,DESCONOCIDO,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,DESCONOCIDO,Paris,DESCONOCIDO,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,DESCONOCIDO,Pasadena,CA,90003,USA,DESCONOCIDO,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,DESCONOCIDO,San Francisco,CA,DESCONOCIDO,USA,DESCONOCIDO,Brown,Julie,Medium

In [ ]:
# =========================
# PREFIX DEL AGENTE
# =========================

prefix = """
Sos un agente inteligente especializado en análisis de datos utilizando pandas.

Tu función es:
- analizar el DataFrame
- responder preguntas en lenguaje natural
- utilizar pandas para consultar información
- generar respuestas claras y precisas

Si ocurre un error:
- intentá reinterpretar la consulta
- corregí automáticamente problemas simples
- continuá utilizando el DataFrame correctamente
"""

print("Prefix configurado correctamente")

Prefix configurado correctamente

In [ ]:
# =========================
# CREAR AGENTE AVANZADO
# =========================

agent = create_pandas_dataframe_agent(
    llm=llm,
    df=df,
    prefix=prefix,
    verbose=True,
    allow_dangerous_code=True,
    handle_parsing_errors=True,
    agent_type="tool-calling"
)

print("Agente avanzado creado correctamente")

Agente avanzado creado correctamente

/usr/local/lib/python3.12/dist-packages/langchain_experimental/agents/agent_toolkits/pandas/base.py:283: UserWarning: Received additional kwargs {'handle_parsing_errors': True} which are no longer supported.
  warnings.warn(

In [ ]:
# =========================
# PRUEBA 1
# =========================

respuesta = agent.invoke(
    "¿Cuántas filas tiene el dataset?"
)

print(respuesta)

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': 'len(df)'}`


2823El dataset tiene **2,823 filas**.

> Finished chain.
{'input': '¿Cuántas filas tiene el dataset?', 'output': 'El dataset tiene **2,823 filas**.'}

In [ ]:
# =========================
# PRUEBA 2
# =========================

try:
    respuesta = agent.invoke(
        "¿Cuál es el producto más vendido?"
    )

    print(respuesta)

except Exception as e:
    print("Ocurrió un error:")
    print(e)

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "df.groupby('productcode')['quantityordered'].sum().idxmax()"}`


S18_3232El producto más vendido, medido por la cantidad total ordenada, es el **producto con código `S18_3232`**.

Si necesitas más detalles sobre este producto (como su nombre, línea o ventas totales), puedo proporcionártelos. ¿Te gustaría que profundice en esta información?

> Finished chain.
{'input': '¿Cuál es el producto más vendido?', 'output': 'El producto más vendido, medido por la cantidad total ordenada, es el **producto con código `S18_3232`**.\n\nSi necesitas más detalles sobre este producto (como su nombre, línea o ventas totales), puedo proporcionártelos. ¿Te gustaría que profundice en esta información?'}

In [ ]:
# =========================
# PRUEBA 3
# =========================

try:
    respuesta = agent.invoke(
        "¿Cuál es el promedio de ventas?"
    )

    print(respuesta)

except Exception as e:
    print("Ocurrió un error:")
    print(e)

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "df['sales'].mean()"}`


3553.889071909316El promedio de ventas en el DataFrame es **3553.89**.

> Finished chain.
{'input': '¿Cuál es el promedio de ventas?', 'output': 'El promedio de ventas en el DataFrame es **3553.89**.'}

In [ ]:
# =========================
# INSTALACIÓN RAG
# =========================

!pip install -q chromadb
!pip install -q sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.3/23.3 MB 45.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 16.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 95.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 78.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 17.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 5.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mistralai 2.4.7 requires opentelemetry-semantic-conventions<0.61,>=0.60b1, but you have opentelemetry-semantic-conventions 0.63b1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.42.1 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.42.1 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.42.1 which is incompatible.

In [ ]:
# =========================
# IMPORTACIONES RAG
# =========================

from langchain_core.documents import Document

from langchain_community.vectorstores import FAISS

from langchain_community.embeddings import HuggingFaceEmbeddings

print("Importaciones RAG correctas")

Importaciones RAG correctas

In [ ]:
# =========================
# CONVERTIR CSV A DOCUMENTOS
# =========================

documentos = []

for index, row in df.iterrows():

    texto = " | ".join(row.astype(str))

    documentos.append(
        Document(page_content=texto)
    )

print("Cantidad de documentos creados:")
print(len(documentos))

Cantidad de documentos creados:
2823

In [ ]:
# =========================
# MODELO DE EMBEDDINGS
# =========================

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("Modelo de embeddings cargado correctamente")

/tmp/ipykernel_24882/852285207.py:5: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Modelo de embeddings cargado correctamente

In [ ]:
# =========================
# INSTALAR FAISS
# =========================

!pip install -q faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 44.4 MB/s eta 0:00:00

In [ ]:
# =========================
# CREAR BASE VECTORIAL
# =========================

vectorstore = FAISS.from_documents(
    documentos,
    embedding_model
)

print("Base vectorial FAISS creada correctamente")

Base vectorial FAISS creada correctamente

In [49]:
# =========================
# CREAR RETRIEVER
# =========================

retriever = vectorstore.as_retriever(
    search_kwargs={"k": 5}
)

print("Retriever configurado correctamente")

Retriever configurado correctamente

In [50]:
# =========================
# PRUEBA RETRIEVER
# =========================

documentos_recuperados = retriever.invoke(
    "producto más vendido"
)

print(documentos_recuperados[0].page_content)

10184 | 28 | 100.0 | 10 | 4409.72 | 11/14/2003 0:00 | Shipped | 4 | 11 | 2003 | Classic Cars | 169 | S18_3232 | Iberia Gift Imports, Corp. | (95) 555 82 82 | C/ Romero, 33 | DESCONOCIDO | Sevilla | DESCONOCIDO | 41101 | Spain | EMEA | Roel | Jose Pedro | Medium

In [51]:
# =========================
# CONSULTA RAG
# =========================

consulta = "¿Cuál es el producto más vendido?"

contexto = retriever.invoke(consulta)

texto_contexto = "\n".join(
    [doc.page_content for doc in contexto]
)

prompt = f"""
Usá el siguiente contexto para responder la pregunta.

Contexto:
{texto_contexto}

Pregunta:
{consulta}
"""

respuesta = llm.invoke(prompt)

print(respuesta.content)

Para determinar el producto más vendido, debemos analizar la columna que indica la **cantidad vendida** (tercer valor en cada línea) y multiplicarla por el **precio de venta** (quinto valor) para obtener el **total de ventas por producto**.

### Cálculos:
1. **Classic Cars (S18_3232)**:
   - Cantidad: 28
   - Precio: 4409.72
   - Total: 28 × 4409.72 = **123,472.16**

2. **Trucks and Buses (S18_2319)**:
   - Cantidad: 46
   - Precio: 5984.14
   - Total: 46 × 5984.14 = **275,270.44**

3. **Trucks and Buses (S32_1268)**:
   - Cantidad: 46
   - Precio: 4607.36
   - Total: 46 × 4607.36 = **211,938.56**

4. **Trucks and Buses (S18_2432)**:
   - Cantidad: 44
   - Precio: 2647.04
   - Total: 44 × 2647.04 = **116,469.76**

5. **Classic Cars (S24_2840)**:
   - Cantidad: 42
   - Precio: 1336.44
   - Total: 42 × 1336.44 = **56,130.48**

### Conclusión:
El producto con el **mayor total de ventas** es:
**Trucks and Buses (S18_2319)** con **275,270.44** en ventas.

*(Nota: Si solo se considera la cantidad vendida sin multiplicar por el precio, el producto más vendido sería "Trucks and Buses" con 46 unidades, pero el criterio económico prioriza el total de ventas).*